/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package guide.to.web.dev;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainTest {
  @Test
  void mainHasAGreeting() {
    Main classUnderTest = new Main();
    assertNotNull(classUnderTest.getGreeting(), "main should have a greeting");
  }
}
